### PR TITLE
Added phpBB forum plugin link

### PR DESCRIPTION
**Pull request by SiteSplat**

### CODE REVIEW

**Comment by LukeHandle** [comment]
Hey, can we get a version hosted on the phpBB addon site?

**Comment by SiteSplat** [comment]
Yep I submitted it last week. However their process is slow. Would be nice to start using the link in my pull request as that is where I offer support for the plugin and my premium themes. Cheers! :)

**Comment by SiteSplat** [comment]
Added the official link, please merge.

**Comment by LukeHandle** [comment]
Thanks for your patience here. I'm closing this out, please see #11

**Pull request closed without merging**
